### PR TITLE
Revert "Merge pull request #23 from isuruf/v3"

### PR DESCRIPTION
**Pull request by isuruf**
This reverts commit 9f00e3357b4473a4152a5c7ae09c1332e157afed, reversing
changes made to 75350cb02ad0dc7037934bd70bb10109d9983fd8.

### CODE REVIEW

**Comment by jakirkham** [comment]
Maybe you are right that we should pin the `toolchain`. I think it is good that you are pursuing this caching work. Though I don't want you to feel pressured by any break this might trigger in all of conda-forge. It definitely takes some effort to get this stuff right. Approaching iteratively and supporting 2 versions of the `toolchain` for a little while might be the way we accomplish this. What do you think?

**Comment by isuruf** [comment]
Yeah, I think having another package like `toolchain3` and slowly moving to it would work.

(Btw, problem with opencv was that this didn't handle pre-compiled headers. I'll have a look over the weekend.)

**Comment by jakirkham** [comment]
We could also release `toolchain` 3 under a non-`main` label. That way it shouldn't be pulled into builds by default, but people can opt-in if they want to try.

**Comment by isuruf** [comment]
Yes, but then you really can't use it without adding the channel in `conda-forge.yml` which would complicate the process.

**Pull request merged**
